service: beer-info-bot

frameworkVersion: "3"

useDotenv: true,

package:
  excludeDevDependencies: true

provider:
  name: aws
  runtime: nodejs18.x
  environment:

plugins:
  - serverless-plugin-typescript
	-	serverless-dotenv-plugin

functions:
  echo:
    handler: handler.beerBot
    events:
      - httpApi:
          path: echo
          method: post
